import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mitra KMIT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {/* Navbar stays on top */}
          <div className={"sticky top-0 z-50"} >
            <Navbar />
          </div>

          {/* Scrollable content in middle */}
          <main className={"flex-1 overflow-y-auto"}>
            {children}
          </main>

          {/* Footer sticks at bottom */}
          <footer className={"sticky bottom-0 z-50 border-t border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-900 py-2"}>
            <div className={"max-w-5xl mx-auto flex items-center justify-center"}>
              <p className={"text-sm text-gray-500 dark:text-gray-400"}>
                &copy; MITRA NSS KMIT {new Date().getFullYear()}
              </p>
            </div>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
